"""Add columns plate_number, tally_number and timestmp to Item model

Revision ID: 9f35211b2700
Revises: e2412789c190
Create Date: 2024-04-19 05:57:55.981841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f35211b2700'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('plate_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('item', sa.Column('tally_number', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('item', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('item', 'timestamp')
    op.drop_column('item', 'tally_number')
    op.drop_column('item', 'plate_number')
    # ### end Alembic commands ###
